# Generated by Django 3.2.6 on 2021-08-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=10)),
                ('description', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[(0, 'Bug'), (1, 'Task'), (2, 'Story'), (3, 'Epic')])),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'In Progress'), (2, 'In Review'), (3, 'Code Complete'), (4, 'Done')], default=0)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('projct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
